### ISSUE TITLE
EOL ACF PRO 5.0 support (?)

### ISSUE THREAD

**Issue by soderlind** [soderlind/acf-field-date-time-picker#105]
Since ACF PRO now has a date and time field, should I remove my support for ACF PRO 5.0 ?

Please vote at [https://github.com/soderlind/acf-field-date-time-picker/issues/105](https://github.com/soderlind/acf-field-date-time-picker/issues/105) by adding a comment to this issue

+1 = Remove
-1 = Keep (note, it's hard to avoid conflict with the built in date and time picker)

**Comment by soderlind** [comment]
+1

**Comment by fabrizim** [comment]
+1 - thanks for your hard work on this plugin
