### ISSUE TITLE
Php error (uncaught error calling undefined function)

### ISSUE THREAD

**Issue by Archie22is** [soderlind/acf-field-date-time-picker#111]
### Description of Problem
Fatal error: Uncaught Error: Call to undefined function write_log()

### Details
* URL of Page exhibiting problem: Any admin post type page with or without plugin
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): All
* Version of WordPress Installed: 4.7.2
* Other plugins installed: Advanced Custom Fields 4.4.11

Happened right after the upgrade to version: 2.1.4 this morning. 

Detailed error message: 
`Fatal error: Uncaught Error: Call to undefined function write_log() in /public/wp-content/plugins/acf-field-date-time-picker/date-time-picker-v4.php:464 Stack trace: #0 /public/wp-content/plugins/acf-field-date-time-picker/date-time-picker-v4.php(365): ACFFieldDateTimePicker->get_js_locale('en-us') #1 /public/wp-includes/class-wp-hook.php(296): ACFFieldDateTimePicker->input_admin_enqueue_scripts() #2 /public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #3 /public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /public/wp-content/plugins/advanced-custom-fields/core/controllers/post.php(117): do_action('acf/input/admin...') #5 /public/wp-includes/class-wp-hook.php(298): acf_controller_post->admin_enqueue_scripts('post.php') #6 /public/wp-content/plugins/acf-field-date-time-picker/date-time-picker-v4.php on line 464`

### Screenshots
N/A

**Comment by soderlind** [comment]
Thank you for reporting this, latest update (2.1.5) fixes this.
