### ISSUE TITLE
UI time picker doesn't run? 

### ISSUE THREAD

**Issue by JesperStender** [soderlind/acf-field-date-time-picker#113]
### Description of Problem
No matter what i select in your plugin, it will just show the standard date picker, and i can't select a time.
Have tried updating, reinstalling, flushing etc. 
There is no console errors but the div with the code isn't being generated, and the calendar isn't being hidden.

I have WP version 4.8.1
ACF 4.4.11

### Screenshots 
![screen shot 2017-08-10 at 14 14 58](https://user-images.githubusercontent.com/27269534/29170151-8e411672-7dd7-11e7-9c05-516efbadbad3.png)
![screen shot 2017-08-10 at 14 15 05](https://user-images.githubusercontent.com/27269534/29170150-8e3abcd2-7dd7-11e7-9ce6-ef1e8683df14.png)

Do you have any idea what is causing this?

**Comment by JesperStender** [comment]
WP Opening hours plugin had a javascript conflict - it has been resolved with the newest update.

**Comment by soderlind** [comment]
Sorry for late response, been on vacation. Glad you found the coulprit.
