### ISSUE TITLE
Timepicker unusable in new Repeater Rows

### ISSUE THREAD

**Issue by madmanlear** [soderlind/acf-field-date-time-picker#88]
Hi,

I'm running the newest version of Wordpress (4.2.2), ACF Pro (5.2.6) and Date-Time-Picker (2.0.18.1).

If you create a field within a repeater that is just a timepicker (no calendar), it will not activate when a new row is added. If the row is saved and then gets output on page load it works fine. But when it's live-loaded focusing on the field does nothing.

Let me know if you need any additional info to replicate. Thanks!

**Comment by lithiumlab** [comment]
This issue also comes out when using acf_form to generate front end forms.
I guess a hook should be included to insert js initialization on appending new fields. (Repeater and Layout fields)

**Comment by gurtfrobe** [comment]
Bump

**Comment by soderlind** [comment]
Latest version of my plugin doesn't support ACF PRO, please use the date and time picker included with ACF PRO
